# Deploys changes on main to my lightsail instance

name: Deploy to Lightsail

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - shell: bash
        env:
          LIGHTSAIL_KEY: ${{ secrets.LIGHTSAIL_KEY }}
        run: |
          echo $LIGHTSAIL_KEY > LightsailDefaultKey-us-west-2.pem
          sudo chmod 600 LightsailDefaultKey-us-west-2.pem
          ssh -o StrictHostKeyChecking no -i LightsailDefaultKey-us-west-2.pem admin@54.213.145.12 "cd grapher; git pull; sudo systemctl restart grapher.service"
