# Deploys changes on main to my lightsail instance

name: Deploy to Lightsail

# Controls when the action will run. 
on:
  workflow_run:
    workflows: ["Clojure CI"]
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - shell: bash
        env:
          LIGHTSAIL_KEY: ${{ secrets.LIGHTSAIL_KEY }}
        run: |
          echo "$LIGHTSAIL_KEY" | tr -d '\r' | ssh-add - > /dev/null
          ssh -o StrictHostKeyChecking=no admin@54.213.145.12 "cd grapher; git pull; sudo systemctl restart grapher.service"
